#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CarouselView.Resource", IsApplication=false)]

namespace CarouselView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public static int animateOnBoundary = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int autoPlay = 2130771969;
			
			// aapt resource value: 0x7F010002
			public static int centered = 2130771970;
			
			// aapt resource value: 0x7F010003
			public static int disableAutoPlayOnUserInteraction = 2130771971;
			
			// aapt resource value: 0x7F010004
			public static int fillColor = 2130771972;
			
			// aapt resource value: 0x7F010005
			public static int indicatorGravity = 2130771973;
			
			// aapt resource value: 0x7F010006
			public static int indicatorMarginHorizontal = 2130771974;
			
			// aapt resource value: 0x7F010007
			public static int indicatorMarginVertical = 2130771975;
			
			// aapt resource value: 0x7F010008
			public static int indicatorOrientation = 2130771976;
			
			// aapt resource value: 0x7F010009
			public static int pageColor = 2130771977;
			
			// aapt resource value: 0x7F01000B
			public static int pageTransformer = 2130771979;
			
			// aapt resource value: 0x7F01000A
			public static int pageTransformInterval = 2130771978;
			
			// aapt resource value: 0x7F01000C
			public static int radius = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public static int slideInterval = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public static int snap = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public static int strokeColor = 2130771983;
			
			// aapt resource value: 0x7F010010
			public static int strokeWidth = 2130771984;
			
			// aapt resource value: 0x7F010011
			public static int vpiCirclePageIndicatorStyle = 2130771985;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F020000
			public static int default_circle_indicator_centered = 2130837504;
			
			// aapt resource value: 0x7F020001
			public static int default_circle_indicator_snap = 2130837505;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public static int default_circle_indicator_fill_color = 2130903040;
			
			// aapt resource value: 0x7F030001
			public static int default_circle_indicator_page_color = 2130903041;
			
			// aapt resource value: 0x7F030002
			public static int default_circle_indicator_stroke_color = 2130903042;
			
			// aapt resource value: 0x7F030003
			public static int vpi__background_holo_dark = 2130903043;
			
			// aapt resource value: 0x7F030004
			public static int vpi__background_holo_light = 2130903044;
			
			// aapt resource value: 0x7F030005
			public static int vpi__bright_foreground_disabled_holo_dark = 2130903045;
			
			// aapt resource value: 0x7F030006
			public static int vpi__bright_foreground_disabled_holo_light = 2130903046;
			
			// aapt resource value: 0x7F030007
			public static int vpi__bright_foreground_holo_dark = 2130903047;
			
			// aapt resource value: 0x7F030008
			public static int vpi__bright_foreground_holo_light = 2130903048;
			
			// aapt resource value: 0x7F030009
			public static int vpi__bright_foreground_inverse_holo_dark = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public static int vpi__bright_foreground_inverse_holo_light = 2130903050;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public static int default_circle_indicator_radius = 2130968576;
			
			// aapt resource value: 0x7F040001
			public static int default_circle_indicator_stroke_width = 2130968577;
			
			// aapt resource value: 0x7F040002
			public static int default_indicator_margin_horizontal = 2130968578;
			
			// aapt resource value: 0x7F040003
			public static int default_indicator_margin_vertical = 2130968579;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public static int bottom = 2131034112;
			
			// aapt resource value: 0x7F050001
			public static int center = 2131034113;
			
			// aapt resource value: 0x7F050002
			public static int center_horizontal = 2131034114;
			
			// aapt resource value: 0x7F050003
			public static int center_vertical = 2131034115;
			
			// aapt resource value: 0x7F050004
			public static int containerViewPager = 2131034116;
			
			// aapt resource value: 0x7F050005
			public static int depth = 2131034117;
			
			// aapt resource value: 0x7F050006
			public static int end = 2131034118;
			
			// aapt resource value: 0x7F050007
			public static int flow = 2131034119;
			
			// aapt resource value: 0x7F050008
			public static int horizontal = 2131034120;
			
			// aapt resource value: 0x7F050009
			public static int indicator = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public static int left = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public static int right = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public static int slide_over = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public static int start = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public static int top = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public static int vertical = 2131034127;
			
			// aapt resource value: 0x7F050010
			public static int zoom = 2131034128;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F060000
			public static int default_circle_indicator_orientation = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public static int view_carousel = 2131165184;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public static int app_name = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000,0x7F010001,0x7F010003,0x7F010004,0x7F010005,0x7F010006,0x7F010007,0x7F010008,0x7F010009,0x7F01000A,0x7F01000B,0x7F01000C,0x7F01000D,0x7F01000E,0x7F01000F,0x7F010010 }
			public static int[] CarouselView = new int[] {
					2130771968,
					2130771969,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 0
			public static int CarouselView_animateOnBoundary = 0;
			
			// aapt resource value: 1
			public static int CarouselView_autoPlay = 1;
			
			// aapt resource value: 2
			public static int CarouselView_disableAutoPlayOnUserInteraction = 2;
			
			// aapt resource value: 3
			public static int CarouselView_fillColor = 3;
			
			// aapt resource value: 4
			public static int CarouselView_indicatorGravity = 4;
			
			// aapt resource value: 5
			public static int CarouselView_indicatorMarginHorizontal = 5;
			
			// aapt resource value: 6
			public static int CarouselView_indicatorMarginVertical = 6;
			
			// aapt resource value: 7
			public static int CarouselView_indicatorOrientation = 7;
			
			// aapt resource value: 8
			public static int CarouselView_pageColor = 8;
			
			// aapt resource value: 10
			public static int CarouselView_pageTransformer = 10;
			
			// aapt resource value: 9
			public static int CarouselView_pageTransformInterval = 9;
			
			// aapt resource value: 11
			public static int CarouselView_radius = 11;
			
			// aapt resource value: 12
			public static int CarouselView_slideInterval = 12;
			
			// aapt resource value: 13
			public static int CarouselView_snap = 13;
			
			// aapt resource value: 14
			public static int CarouselView_strokeColor = 14;
			
			// aapt resource value: 15
			public static int CarouselView_strokeWidth = 15;
			
			// aapt resource value: { 0x10100C4,0x10100D4,0x7F010002,0x7F010004,0x7F010009,0x7F01000C,0x7F01000E,0x7F01000F,0x7F010010 }
			public static int[] CirclePageIndicator = new int[] {
					16842948,
					16842964,
					2130771970,
					2130771972,
					2130771977,
					2130771980,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 1
			public static int CirclePageIndicator_android_background = 1;
			
			// aapt resource value: 0
			public static int CirclePageIndicator_android_orientation = 0;
			
			// aapt resource value: 2
			public static int CirclePageIndicator_centered = 2;
			
			// aapt resource value: 3
			public static int CirclePageIndicator_fillColor = 3;
			
			// aapt resource value: 4
			public static int CirclePageIndicator_pageColor = 4;
			
			// aapt resource value: 5
			public static int CirclePageIndicator_radius = 5;
			
			// aapt resource value: 6
			public static int CirclePageIndicator_snap = 6;
			
			// aapt resource value: 7
			public static int CirclePageIndicator_strokeColor = 7;
			
			// aapt resource value: 8
			public static int CirclePageIndicator_strokeWidth = 8;
			
			// aapt resource value: { 0x7F010011 }
			public static int[] ViewPagerIndicator = new int[] {
					2130771985};
			
			// aapt resource value: 0
			public static int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
